### ISSUE TITLE
KerasPolicy example

### ISSUE THREAD

**Issue by RochaCarla** [souvikg10/rasa-core-experiment#1]
Hey,
I guess we've talked today at rasa summit. 
Do you by any chance have a project testing keraspolicy? 
we are having hard time to implement it robustly..

**Comment by souvikg10** [comment]
Hi
I have just published the article linked to this repo. I have an example here but it is really to dissect the inner workings of Rasa. I wouldn’t say that it works in every case yet. I am writing another another article on optimisation of stories
For now I have this
https://link.medium.com/tOFSbiM2eR

**Comment by RochaCarla** [comment]
Thanks for the feedback! I looked very quickly your article and it looks very interesting. I'll take a closer look! Thanks. 
If you find any complete project using keraspolicy well, please share it ;P

**Comment by souvikg10** [comment]
I will eventually optimise this project using hyperparameters. I initially thought of doing so for the same timeline but then it would have taken me some more time as optimisation will require evaluation as well. It will be in my next article. Around next week

**Comment by souvikg10** [comment]
@RochaCarla if you have a use-case in mind, apart from this one, I am happy to collaborate on using the right classifier to build a fluid chatbot. For the moment, since i do it on my own, i don't have any usecase per say.

**Comment by RochaCarla** [comment]
Thanks for all feedbacks.. Were developing a bigger bot (with longer stories and many for intents). When you try to scale a chatbot, the hyperparameters make all the difference and I didn`t find any project that we could use as a reference/example.
Feel free to visit our repository (it is in Portuguese though)

https://github.com/lappis-unb/rouana

**Comment by souvikg10** [comment]
Okay, I guess you will need a lot of stories for neural network to perform well and i found two useful hyper parameter (max_history and augmentation factor). 

You can also try the FullDialogueHistoryFeaturizer. In my company i tried to play around with a lot of different hyperparameter to see what really fits the model and ultimately it wasn't just the model but the questions that the bot asks to the user as well, that makes a huge difference. There are no generic solution

I noticed you are passing the default parameters of Keras Policy, you can update them to see what fits your dialogue. There is also a new evaluation script. I am writing about it for the moment :)

**Comment by RochaCarla** [comment]
Thanks for your help! Currently, we`re not even using KerasPolicy (we used the default parameters, but we are using only one huge story with checkpoints to guide the conversation, like traditional bots). We are trying to learn keraspolicy to evolve the bot to a more complex behavior.

I guess I have all the information I need to study and try some scenarios. I'll close then the issue ;)
Thanks again for your help!
Cheers
